import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'rsuite/dist/rsuite-no-reset.min.css';
import Header  from './../components/header/Header';
import { CustomProvider } from 'rsuite';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>

      </title>
      <body className={inter.className}>
        <Header/>
        <CustomProvider>{children}</CustomProvider>
        </body>
    </html>
  );
}
